### ISSUE TITLE
Markdown语法与外挂标签写法汇总 | HCY's Blog

### ISSUE THREAD

**Issue by Luminet2023** [Luminet2023/talk#3]
https://blog.hcyhomo.cc/posts/2013454d.html 

 🥧本文汇总Markdown格式以及外挂标签在网页端的渲染效果，可作为文档进行查询

**Comment by jonncrsas** [comment]
114514

**Comment by jonncrsas** [comment]
hi

**Comment by jonncrsas** [comment]
{% image https://webstatic.hcyhomo.cc/photo/elysia.jpg, width=400px %}

**Comment by jonncrsas** [comment]
![code](https://webstatic.hcyhomo.cc/photo/elysia.jpg)
